[package]
name = "simple-riscv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type=["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"

bitvec = "1.0.1"
bitpattern = "0.1.0"
bitmatch = "0.1.1"